### ISSUE TITLE
SMSKitting is halting while in the app.

### ISSUE THREAD

**Issue by kgilliam3662** [ConceptualSystems/kit-mobile-portable#2]
Plus I still seeing a dialog stating SMSKitting has stopped working several times today!  Humm

![Snap135](https://user-images.githubusercontent.com/34950529/56764701-f79d8280-676a-11e9-9d1f-b3c43b123a79.jpg)

**Comment by moonlightcheese** [comment]
I was able to confirm the issue:

2019-04-29 03:32:19.098 7516-8915/? E/AndroidRuntime: FATAL EXCEPTION: Thread-5
    Process: com.conceptualsystems.kitting, PID: 7516
    android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=671 (# cursors opened by this proc=671)
        at android.database.CursorWindow.<init>(CursorWindow.java:108)
        at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
        at android.database.sqlite.SQLiteCursor.clearOrCreateWindow(SQLiteCursor.java:309)
        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:147)
        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:141)
        at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
        at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:259)
        at com.conceptualsystems.android.net.OutboundMessageManager.getInterval(OutboundMessageManager.java:109)
        at com.conceptualsystems.android.net.OutboundMessageManager.access$200(OutboundMessageManager.java:27)
        at com.conceptualsystems.android.net.OutboundMessageManager$OutboundSenderThread.run(OutboundMessageManager.java:209)

This is due to the OutboundMessageManager flooding the system CursorWindow by not releasing database Cursors.

Fixed in 2.24

**Comment by kgilliam3662** [comment]
Thanks will get SMSKitting 2.24 and SMSMobile 1.52 loaded onto my tablet and test on Tuesday.

Keith
